### ISSUE TITLE
Animate coral

### ISSUE THREAD

**Issue by andyroberson** [andyroberson/j584-coral-game#22]
blinking? eyes following mouse? 

making it sad?

**Comment by kristiwalker** [comment]
For blinking possibility: Would you just make the the spritesheet for this loop throughout the entire game? Will its rhythm get messed up when they run tests and the images are different?

For eyes following mouse: Is this something we can do with easle.js? If yes, and we're definitely going to do this, let me know and I'll get you the eyes (or just pupils?) saved out separately.

For making it sad: The 10 phases I already sent over do not have the face phasing slowly to each face. It transitions immediately from happy to discontent to sad. I just want to see how it looks when they're put together before I add in a lot more frames. This is my first time doing an old-school animation, so I'm not sure how much more we need to make it realistic, or if it's going to look good as is. Trial and error will be the best approach here.

**Comment by andyroberson** [comment]
Yes spritesheet for blinking eyes, but they need to be on the coral and have the face so that i don't have to position the eyes. Which also means I'll need a blinking eye version of happy unbleached blinking, medium bleached medium expression blinkng, and sad bleached blinking if we want it to be blinking all teh time. 

I've done work with old school animations, and I think expressions changing that immediately mgiht be a bit abrupt. Might be better to have transitional faces in between them so it's immediately apparent that changing color is bad. I.e, it's not almost halfway bleached and still smiling, it's almost halfway bleached and the facial expression was getting sadder and sadder the whole time. Does that make sense? 

At this point in the project, I don't think eyes following the mouse will be possible, but I think if it's blinking it'll be enough interaction.
