### ISSUE TITLE
Pop up introduction

### ISSUE THREAD

**Issue by andyroberson** [andyroberson/j584-coral-game#6]
When first visiting the game, pop up that asks if you want a tour around the aquarium to learn the controls.

If yes, pop ups for each element to explain game. 
If no, go straight to starting the game.

Should have option to close this at any time and skip popups to start game.

Andy already found a plugin for this!

**Comment by kristiwalker** [comment]
Ahhhhhh okay. Can you send me the plugin so I can see exactly how it works? Functionality is kind of affecting my phrasing of the copy.

**Comment by andyroberson** [comment]
Don't worry at all about phrasing. I saved this plugin link on a document somewhere so I'll have to dig for it and send it to you later, but we'll have the log that automatically scrolls at the bottom of the game, so it'll be able to display even longer text formats, so we could always be like a popup that says "The coral has bleached! Check the log for reasons this might have happened" and have more detail in the log
